[server]
port = 8282
host = "127.0.0.1"
secret_key = "CHANGE_ME"
base_url = "http://localhost:8282"
verify_requests = false

[cache]
enabled = true
# will get cached in /var/tmp/youtubei.js if you specify /var/tmp
# you need to change the --allow-write from deno run too
directory = "/var/tmp"

[networking]
#proxy = ""
# Enable YouTube new video format UMP
ump = false

[jobs]

[jobs.youtube_session]
po_token_enabled = true
frequency = "*/5 * * * *"

[youtube_session]
oauth_enabled = false
cookies = ""